INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=530&awinaffid=125132&clickref=&p=", name="7dayshop.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1281&awinaffid=125132&clickref=&p=", name="247 Blinds";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1552&awinaffid=125132&clickref=&p=", name="991.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=645&awinaffid=125132&clickref=&p=", name="A1Gifts.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2485&awinaffid=125132&clickref=&p=", name="ActivInstinct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=802&awinaffid=125132&clickref=&p=", name="Activity Superstore";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2069&awinaffid=125132&clickref=&p=", name="Adnams Cellar &amp; Kitchen";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3220&awinaffid=125132&clickref=&p=", name="Advanced Headphones";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=361&awinaffid=125132&clickref=&p=", name="Advanced MP3 Players";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3&awinaffid=125132&clickref=&p=", name="Affiliate Window";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3494&awinaffid=125132&clickref=&p=", name="Air Parks";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=980&awinaffid=125132&clickref=&p=", name="AJ Electronics Limited";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=605&awinaffid=125132&clickref=&p=", name="All Jigsaw Puzzles";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=984&awinaffid=125132&clickref=&p=", name="Alpha Rooms";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3023&awinaffid=125132&clickref=&p=", name="Ambrose Wilson";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3142&awinaffid=125132&clickref=&p=", name="Ann Summers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2673&awinaffid=125132&clickref=&p=", name="anyvan";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1635&awinaffid=125132&clickref=&p=", name="Arena Flowers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3201&awinaffid=125132&clickref=&p=", name="Atlantic Shopping";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1356&awinaffid=125132&clickref=&p=", name="Attractiontix";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=225&awinaffid=125132&clickref=&p=", name="Auctionair";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3334&awinaffid=125132&clickref=&p=", name="AX Paris";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=427&awinaffid=125132&clickref=&p=", name="BananaShoes Limited";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2476&awinaffid=125132&clickref=&p=", name="Barcelo Hotels &amp; Resorts";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2412&awinaffid=125132&clickref=&p=", name="Barmans.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2694&awinaffid=125132&clickref=&p=", name="Base.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1021&awinaffid=125132&clickref=&p=", name="Bathroom Heaven";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=369&awinaffid=125132&clickref=&p=", name="Be Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=962&awinaffid=125132&clickref=&p=", name="Bed Star Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3175&awinaffid=125132&clickref=&p=", name="Bee.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3174&awinaffid=125132&clickref=&p=", name="Bensons For Beds";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1287&awinaffid=125132&clickref=&p=", name="Bernards Door Furniture Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1337&awinaffid=125132&clickref=&p=", name="Bespoke Gift Company";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2167&awinaffid=125132&clickref=&p=", name="Big Bathroom Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1702&awinaffid=125132&clickref=&p=", name="BigRedWarehouse";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=732&awinaffid=125132&clickref=&p=", name="Bizzy Balloons";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1520&awinaffid=125132&clickref=&p=", name="Blacks";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=526&awinaffid=125132&clickref=&p=", name="Blinds 2 Go - Designer Window Blinds";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1670&awinaffid=125132&clickref=&p=", name="Blooming Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1824&awinaffid=125132&clickref=&p=", name="Blue Chip Holidays";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2387&awinaffid=125132&clickref=&p=", name="Born Gifted";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3192&awinaffid=125132&clickref=&p=", name="Borro";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2060&awinaffid=125132&clickref=&p=", name="Branch309.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1728&awinaffid=125132&clickref=&p=", name="BREAD Card";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3633&awinaffid=125132&clickref=&p=", name="British Corner Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2430&awinaffid=125132&clickref=&p=", name="Brook Taverner";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=608&awinaffid=125132&clickref=&p=", name="Brown Bag Clothing Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=239&awinaffid=125132&clickref=&p=", name="Budget Batteries";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=488&awinaffid=125132&clickref=&p=", name="Bunches.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2607&awinaffid=125132&clickref=&p=", name="Business IT Online Office Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=368&awinaffid=125132&clickref=&p=", name="Butonz";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=273&awinaffid=125132&clickref=&p=", name="Buyagift.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3668&awinaffid=125132&clickref=&p=", name="Buyhair.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=736&awinaffid=125132&clickref=&p=", name="Cadbury Gifts Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2676&awinaffid=125132&clickref=&p=", name="Canterbury.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=808&awinaffid=125132&clickref=&p=", name="CartridgeMonkey";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1726&awinaffid=125132&clickref=&p=", name="Casio Online";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=307&awinaffid=125132&clickref=&p=", name="Cast In Style";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2625&awinaffid=125132&clickref=&p=", name="Catalonia Hoteles";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1838&awinaffid=125132&clickref=&p=", name="CG Golf";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2706&awinaffid=125132&clickref=&p=", name="Chantry Digital";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3358&awinaffid=125132&clickref=&p=", name="Chapel Interiors Wilmslow";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2702&awinaffid=125132&clickref=&p=", name="Chappell Of Bond Street";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2418&awinaffid=125132&clickref=&p=", name="Chargrilled";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2332&awinaffid=125132&clickref=&p=", name="Cheap Suites";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=350&awinaffid=125132&clickref=&p=", name="Chocolate Trading Company";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1240&awinaffid=125132&clickref=&p=", name="Chums Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2864&awinaffid=125132&clickref=&p=", name="Cinderella Shoes";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1459&awinaffid=125132&clickref=&p=", name="Clare Florist";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3747&awinaffid=125132&clickref=&p=", name="Click Fragrance";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2849&awinaffid=125132&clickref=&p=", name="Clickgolf.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3357&awinaffid=125132&clickref=&p=", name="Clogau Gold";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2303&awinaffid=125132&clickref=&p=", name="Club-Cleo - The Science of Health &amp; Beauty";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2806&awinaffid=125132&clickref=&p=", name="Coast &amp; Country Cottages";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2677&awinaffid=125132&clickref=&p=", name="Consoles and Gadgets";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1288&awinaffid=125132&clickref=&p=", name="Cook In Style";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=748&awinaffid=125132&clickref=&p=", name="Cosmic Superstore Gifts";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1806&awinaffid=125132&clickref=&p=", name="Cosyfeet";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3064&awinaffid=125132&clickref=&p=", name="Crave Maternity";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=295&awinaffid=125132&clickref=&p=", name="Create";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3524&awinaffid=125132&clickref=&p=", name="Crieff Hydro Hotel &amp; Resort";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=205&awinaffid=125132&clickref=&p=", name="Crotchet Classical Music";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=293&awinaffid=125132&clickref=&p=", name="CXLondon.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1148&awinaffid=125132&clickref=&p=", name="Darlings of Chelsea";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=433&awinaffid=125132&clickref=&p=", name="Designer Discount";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2761&awinaffid=125132&clickref=&p=", name="Design Hotels";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=355&awinaffid=125132&clickref=&p=", name="DesperateSeller.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2657&awinaffid=125132&clickref=&p=", name="DevilWear";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3376&awinaffid=125132&clickref=&p=", name="Diablo Skinz";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2725&awinaffid=125132&clickref=&p=", name="Diamond Manufacturers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2394&awinaffid=125132&clickref=&p=", name="Discount Supplements";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=513&awinaffid=125132&clickref=&p=", name="DIY Tools";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1901&awinaffid=125132&clickref=&p=", name="DoSomethingDifferent.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1847&awinaffid=125132&clickref=&p=", name="easyOffice";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2666&awinaffid=125132&clickref=&p=", name="ebookshoppe";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2734&awinaffid=125132&clickref=&p=", name="eChemist";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1311&awinaffid=125132&clickref=&p=", name="Electrical Discount UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2276&awinaffid=125132&clickref=&p=", name="Electrical Experience";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3269&awinaffid=125132&clickref=&p=", name="Electrotown";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1221&awinaffid=125132&clickref=&p=", name="Europc";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2623&awinaffid=125132&clickref=&p=", name="Eurostarshotels";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1453&awinaffid=125132&clickref=&p=", name="Evengreener";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=411&awinaffid=125132&clickref=&p=", name="EveryoneDoesIT";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1151&awinaffid=125132&clickref=&p=", name="Evocal Ltd.";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1241&awinaffid=125132&clickref=&p=", name="Exclusive RMC Offers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1566&awinaffid=125132&clickref=&p=", name="Fantasy League";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3030&awinaffid=125132&clickref=&p=", name="Fashion World";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2797&awinaffid=125132&clickref=&p=", name="Fatcheese.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3028&awinaffid=125132&clickref=&p=", name="Fifty Plus";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=689&awinaffid=125132&clickref=&p=", name="Find Jewellery + Find Watches";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=998&awinaffid=125132&clickref=&p=", name="Findmeagift.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=120&awinaffid=125132&clickref=&p=", name="Firebrand Training";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2829&awinaffid=125132&clickref=&p=", name="First TransPennine Express";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2863&awinaffid=125132&clickref=&p=", name="Fitbug Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=899&awinaffid=125132&clickref=&p=", name="Fitness Options";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3145&awinaffid=125132&clickref=&p=", name="FlyTorair";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1608&awinaffid=125132&clickref=&p=", name="Freestylextreme";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2686&awinaffid=125132&clickref=&p=", name="Fun4Kids";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=495&awinaffid=125132&clickref=&p=", name="Furniture 123";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1149&awinaffid=125132&clickref=&p=", name="Furnitureatwork";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2287&awinaffid=125132&clickref=&p=", name="Furniture Village";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=381&awinaffid=125132&clickref=&p=", name="Gadgets.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=547&awinaffid=125132&clickref=&p=", name="Gameseek";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2908&awinaffid=125132&clickref=&p=", name="Gamola Golf";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=258&awinaffid=125132&clickref=&p=", name="Garden Pharmacy";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1117&awinaffid=125132&clickref=&p=", name="Gear 4 Music";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2421&awinaffid=125132&clickref=&p=", name="Gemondo Jewellery";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3590&awinaffid=125132&clickref=&p=", name="Geniegadgets.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3632&awinaffid=125132&clickref=&p=", name="Get Pet Supplies";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1965&awinaffid=125132&clickref=&p=", name="Gizoo";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2881&awinaffid=125132&clickref=&p=", name="Gizzmo Heaven";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2894&awinaffid=125132&clickref=&p=", name="Goddiva";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2848&awinaffid=125132&clickref=&p=", name="Golf Gear Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1964&awinaffid=125132&clickref=&p=", name="Golfonline";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3341&awinaffid=125132&clickref=&p=", name="Golf Store Europe";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3040&awinaffid=125132&clickref=&p=", name="Gray and Osbourn";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2701&awinaffid=125132&clickref=&p=", name="Great Days Out";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2388&awinaffid=125132&clickref=&p=", name="Gymcompany";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2862&awinaffid=125132&clickref=&p=", name="Half Price Perfumes";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3460&awinaffid=125132&clickref=&p=", name="Hallstone Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2828&awinaffid=125132&clickref=&p=", name="Hargroves Cycles";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=856&awinaffid=125132&clickref=&p=", name="Health and Essential Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3551&awinaffid=125132&clickref=&p=", name="HeatandPlumb.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2917&awinaffid=125132&clickref=&p=", name="Henleys Clothing";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3039&awinaffid=125132&clickref=&p=", name="High and Mighty";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2567&awinaffid=125132&clickref=&p=", name="hipotels.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=830&awinaffid=125132&clickref=&p=", name="Holdall";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3496&awinaffid=125132&clickref=&p=", name="Holiday Extras";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1319&awinaffid=125132&clickref=&p=", name="Holiday Taxis";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2107&awinaffid=125132&clickref=&p=", name="Home and Garden Gifts";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3144&awinaffid=125132&clickref=&p=", name="Hotel Gifts &amp; Experience Vouchers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2760&awinaffid=125132&clickref=&p=", name="Hotels Viva";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1452&awinaffid=125132&clickref=&p=", name="Hot Floors UK Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2803&awinaffid=125132&clickref=&p=", name="Hotusa Hotels";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3031&awinaffid=125132&clickref=&p=", name="House of Bath";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=111&awinaffid=125132&clickref=&p=", name="HouseWeb";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3133&awinaffid=125132&clickref=&p=", name="Hughes Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1188&awinaffid=125132&clickref=&p=", name="Icons";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2164&awinaffid=125132&clickref=&p=", name="Idlewild London";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2593&awinaffid=125132&clickref=&p=", name="Imagine Ireland";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=260&awinaffid=125132&clickref=&p=", name="Ink Factory";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2277&awinaffid=125132&clickref=&p=", name="InkXpress Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1585&awinaffid=125132&clickref=&p=", name="Insurance Choice";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2546&awinaffid=125132&clickref=&p=", name="Insure4sport";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1250&awinaffid=125132&clickref=&p=", name="Internet-Ink";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=129&awinaffid=125132&clickref=&p=", name="InterRose";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2251&awinaffid=125132&clickref=&p=", name="iViewCameras";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3026&awinaffid=125132&clickref=&p=", name="Jacamo";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3099&awinaffid=125132&clickref=&p=", name="Jacobs Digital";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3032&awinaffid=125132&clickref=&p=", name="JD Williams";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3252&awinaffid=125132&clickref=&p=", name="Jean-Patrique Cookware";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1485&awinaffid=125132&clickref=&p=", name="Jersey Plants Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3033&awinaffid=125132&clickref=&p=", name="Julipa";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=382&awinaffid=125132&clickref=&p=", name="Karaoke Island";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2583&awinaffid=125132&clickref=&p=", name="Keeperskit";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2191&awinaffid=125132&clickref=&p=", name="Kiddies Kingdom";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3612&awinaffid=125132&clickref=&p=", name="Kingolotto";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3253&awinaffid=125132&clickref=&p=", name="LA Muscle";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2063&awinaffid=125132&clickref=&p=", name="Leisure Vouchers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2658&awinaffid=125132&clickref=&p=", name="lenstore.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1439&awinaffid=125132&clickref=&p=", name="LessBounce";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2230&awinaffid=125132&clickref=&p=", name="Light In Style";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1246&awinaffid=125132&clickref=&p=", name="Ligo Electronics Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=838&awinaffid=125132&clickref=&p=", name="Locks Online";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1305&awinaffid=125132&clickref=&p=", name="London Fine Foods Group";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=610&awinaffid=125132&clickref=&p=", name="LondonTheatreDirect.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1850&awinaffid=125132&clickref=&p=", name="Loudclothing.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2517&awinaffid=125132&clickref=&p=", name="Lovell Rugby Limited";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2518&awinaffid=125132&clickref=&p=", name="Lovell Soccer";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=134&awinaffid=125132&clickref=&p=", name="MagicTricks.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3396&awinaffid=125132&clickref=&p=", name="Malev Hungarian Airlines";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2934&awinaffid=125132&clickref=&p=", name="Manstores.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1256&awinaffid=125132&clickref=&p=", name="Maplin Electronics Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3029&awinaffid=125132&clickref=&p=", name="Marisota";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1867&awinaffid=125132&clickref=&p=", name="Mattress Online";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3003&awinaffid=125132&clickref=&p=", name="MaxCleavage.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1230&awinaffid=125132&clickref=&p=", name="Mean and Green";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2465&awinaffid=125132&clickref=&p=", name="Media Storehouse";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1334&awinaffid=125132&clickref=&p=", name="Memory Foam Warehouse";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3135&awinaffid=125132&clickref=&p=", name="Menkind";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1521&awinaffid=125132&clickref=&p=", name="Millets";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2478&awinaffid=125132&clickref=&p=", name="Mintprice";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2872&awinaffid=125132&clickref=&p=", name="Missguided";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2106&awinaffid=125132&clickref=&p=", name="Mobile Fun";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=380&awinaffid=125132&clickref=&p=", name="Mobiles.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3159&awinaffid=125132&clickref=&p=", name="Moko Chocolates";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2813&awinaffid=125132&clickref=&p=", name="Money4MyMobile";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3596&awinaffid=125132&clickref=&p=", name="Monster Supplements";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2532&awinaffid=125132&clickref=&p=", name="MotelRocks.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3653&awinaffid=125132&clickref=&p=", name="Mountain Warehouse";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2609&awinaffid=125132&clickref=&p=", name="MovieMail Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3545&awinaffid=125132&clickref=&p=", name="Multiyork Furniture";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2620&awinaffid=125132&clickref=&p=", name="MultizoneAV.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3119&awinaffid=125132&clickref=&p=", name="Musto.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1152&awinaffid=125132&clickref=&p=", name="MyMemory";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1146&awinaffid=125132&clickref=&p=", name="Nabru";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=897&awinaffid=125132&clickref=&p=", name="Namesco Limited";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2411&awinaffid=125132&clickref=&p=", name="National Express Eurolines";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=976&awinaffid=125132&clickref=&p=", name="Nature's Own";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3316&awinaffid=125132&clickref=&p=", name="NCP";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=182&awinaffid=125132&clickref=&p=", name="Needapresent.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2774&awinaffid=125132&clickref=&p=", name="Ness";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1379&awinaffid=125132&clickref=&p=", name="Nets2go";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2333&awinaffid=125132&clickref=&p=", name="Next Bathrooms";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3536&awinaffid=125132&clickref=&p=", name="Next Day DIY";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3246&awinaffid=125132&clickref=&p=", name="NITE INTERNATIONAL";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3634&awinaffid=125132&clickref=&p=", name="NONNON";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1498&awinaffid=125132&clickref=&p=", name="Northern Tool Equipment Co UK Limited";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2152&awinaffid=125132&clickref=&p=", name="Oakfurnitureland";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2566&awinaffid=125132&clickref=&p=", name="Oak Furniture Solutions";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1111&awinaffid=125132&clickref=&p=", name="OfficeGiant";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=173&awinaffid=125132&clickref=&p=", name="OFFTEK Computer Memory Upgrades";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=290&awinaffid=125132&clickref=&p=", name="Oneposter.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2611&awinaffid=125132&clickref=&p=", name="OnlineClinic";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1688&awinaffid=125132&clickref=&p=", name="Orchira";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2495&awinaffid=125132&clickref=&p=", name="Ordnance Survey";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2951&awinaffid=125132&clickref=&p=", name="Oregon Scientific";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2456&awinaffid=125132&clickref=&p=", name="Origin Publishing Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2637&awinaffid=125132&clickref=&p=", name="Ortak Jewellery";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=269&awinaffid=125132&clickref=&p=", name="OutdoorGear UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3136&awinaffid=125132&clickref=&p=", name="Oyyy";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1998&awinaffid=125132&clickref=&p=", name="Parcel2Go";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3495&awinaffid=125132&clickref=&p=", name="Park Bcp";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1738&awinaffid=125132&clickref=&p=", name="Park Holidays UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=56&awinaffid=125132&clickref=&p=", name="PartyBox";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1579&awinaffid=125132&clickref=&p=", name="Party Casino";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=659&awinaffid=125132&clickref=&p=", name="Party Delights";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2268&awinaffid=125132&clickref=&p=", name="passion8";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2956&awinaffid=125132&clickref=&p=", name="Perfume Plus Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3643&awinaffid=125132&clickref=&p=", name="Pharmacy First";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2986&awinaffid=125132&clickref=&p=", name="Pharmacy Place Online Pharmacy";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1417&awinaffid=125132&clickref=&p=", name="Phd Fitness";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1137&awinaffid=125132&clickref=&p=", name="PhotoBox";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1350&awinaffid=125132&clickref=&p=", name="PhysioRoom.com Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2528&awinaffid=125132&clickref=&p=", name="Pierre Vacances";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3504&awinaffid=125132&clickref=&p=", name="Pirate-Parfum.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=799&awinaffid=125132&clickref=&p=", name="Plain Lazy";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=831&awinaffid=125132&clickref=&p=", name="PlanetNumbers.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3009&awinaffid=125132&clickref=&p=", name="Police";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=425&awinaffid=125132&clickref=&p=", name="Post-a-Rose";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3035&awinaffid=125132&clickref=&p=", name="Premier Man";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3398&awinaffid=125132&clickref=&p=", name="Presents for Men";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=164&awinaffid=125132&clickref=&p=", name="Prezzybox";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3552&awinaffid=125132&clickref=&p=", name="Primus Saver";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1931&awinaffid=125132&clickref=&p=", name="PrinterInks";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3510&awinaffid=125132&clickref=&p=", name="Pro-Trampolines";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3648&awinaffid=125132&clickref=&p=", name="Professional Glasses";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1310&awinaffid=125132&clickref=&p=", name="Quiz";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1799&awinaffid=125132&clickref=&p=", name="Rapid Online - Rapid Electronics Ltd.";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2804&awinaffid=125132&clickref=&p=", name="Red Candy Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3231&awinaffid=125132&clickref=&p=", name="Rise Fashion";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2630&awinaffid=125132&clickref=&p=", name="Riu Hotels &amp; resorts";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=875&awinaffid=125132&clickref=&p=", name="Savapoint";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1732&awinaffid=125132&clickref=&p=", name="Saverstore";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=813&awinaffid=125132&clickref=&p=", name="Scottsdale Golf";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1547&awinaffid=125132&clickref=&p=", name="Seatwave.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=964&awinaffid=125132&clickref=&p=", name="Serenata Flowers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2242&awinaffid=125132&clickref=&p=", name="Serversdirect";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1744&awinaffid=125132&clickref=&p=", name="Sharp";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1043&awinaffid=125132&clickref=&p=", name="Shirtcity.co.uk - design your shirt";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=506&awinaffid=125132&clickref=&p=", name="Shoesinternational.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2943&awinaffid=125132&clickref=&p=", name="ShopTo.Net";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1017&awinaffid=125132&clickref=&p=", name="ShortBreaks Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1345&awinaffid=125132&clickref=&p=", name="Shot Dead In The Head";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3027&awinaffid=125132&clickref=&p=", name="Simply Be";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1295&awinaffid=125132&clickref=&p=", name="Simply Beach";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1296&awinaffid=125132&clickref=&p=", name="Simply Hike";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2506&awinaffid=125132&clickref=&p=", name="Simply Home Entertainment";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1297&awinaffid=125132&clickref=&p=", name="Simply Piste";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1192&awinaffid=125132&clickref=&p=", name="Simply Scuba Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1294&awinaffid=125132&clickref=&p=", name="Simply Swim";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3024&awinaffid=125132&clickref=&p=", name="Simply Yours";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1615&awinaffid=125132&clickref=&p=", name="Skinlight Cosmetics";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=761&awinaffid=125132&clickref=&p=", name="Slapiton";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2749&awinaffid=125132&clickref=&p=", name="Smart Buy Glasses";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2865&awinaffid=125132&clickref=&p=", name="Soape";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1374&awinaffid=125132&clickref=&p=", name="Sock Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=161&awinaffid=125132&clickref=&p=", name="Song Galaxy";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3489&awinaffid=125132&clickref=&p=", name="SpaBreaks.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=535&awinaffid=125132&clickref=&p=", name="Sparkling Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2638&awinaffid=125132&clickref=&p=", name="Spartoo.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=462&awinaffid=125132&clickref=&p=", name="Speed Dater";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1273&awinaffid=125132&clickref=&p=", name="Spirit of Sport";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1463&awinaffid=125132&clickref=&p=", name="Sport and Leisure UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2668&awinaffid=125132&clickref=&p=", name="Stagebeat";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2507&awinaffid=125132&clickref=&p=", name="St Michel Hotels";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2112&awinaffid=125132&clickref=&p=", name="Strand Palace Hotel";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2449&awinaffid=125132&clickref=&p=", name="Strawberry Fool";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2269&awinaffid=125132&clickref=&p=", name="Stressnomore";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3148&awinaffid=125132&clickref=&p=", name="Stylistpick";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=974&awinaffid=125132&clickref=&p=", name="SubsideSports.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=325&awinaffid=125132&clickref=&p=", name="SuitsMen.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2537&awinaffid=125132&clickref=&p=", name="Sweatband.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=4&awinaffid=125132&clickref=&p=", name="Swerve";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3317&awinaffid=125132&clickref=&p=", name="Sykes Cottages";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2931&awinaffid=125132&clickref=&p=", name="Teds-Shed";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3036&awinaffid=125132&clickref=&p=", name="That's my Style";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3359&awinaffid=125132&clickref=&p=", name="The Airport Parking Company";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1936&awinaffid=125132&clickref=&p=", name="Theatre Tickets Direct";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1818&awinaffid=125132&clickref=&p=", name="The Beauty Room";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3228&awinaffid=125132&clickref=&p=", name="The Brilliant Gift Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1121&awinaffid=125132&clickref=&p=", name="The Classic Motor Show NEC";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=61&awinaffid=125132&clickref=&p=", name="TheDrinkShop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3297&awinaffid=125132&clickref=&p=", name="The Garden Furniture Centre Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2659&awinaffid=125132&clickref=&p=", name="The Gentlemans Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2535&awinaffid=125132&clickref=&p=", name="The Golfers Club";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2558&awinaffid=125132&clickref=&p=", name="The Gym Website";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2960&awinaffid=125132&clickref=&p=", name="TheKitchenApplianceStore";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3130&awinaffid=125132&clickref=&p=", name="The Menswear Site";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1006&awinaffid=125132&clickref=&p=", name="The Safe Shop";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3020&awinaffid=125132&clickref=&p=", name="The Sofa Company";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2062&awinaffid=125132&clickref=&p=", name="The Virgin Voucher";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2556&awinaffid=125132&clickref=&p=", name="Thomson Al Fresco";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=680&awinaffid=125132&clickref=&p=", name="Thruxton Motorsport Centre";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=352&awinaffid=125132&clickref=&p=", name="Tightsplease";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=317&awinaffid=125132&clickref=&p=", name="Toffs Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=496&awinaffid=125132&clickref=&p=", name="Tooled Up";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2751&awinaffid=125132&clickref=&p=", name="Topdoginsurance";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2284&awinaffid=125132&clickref=&p=", name="Topps Tiles Plc";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2121&awinaffid=125132&clickref=&p=", name="Top up TV";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2450&awinaffid=125132&clickref=&p=", name="Totally Funky";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3484&awinaffid=125132&clickref=&p=", name="totes ISOTONER";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1878&awinaffid=125132&clickref=&p=", name="Trampled Underfoot";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2968&awinaffid=125132&clickref=&p=", name="Trampoline Warehouse";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=465&awinaffid=125132&clickref=&p=", name="Tribal UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2578&awinaffid=125132&clickref=&p=", name="Trunki";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3019&awinaffid=125132&clickref=&p=", name="Tub Collection";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=851&awinaffid=125132&clickref=&p=", name="TV Cables";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2882&awinaffid=125132&clickref=&p=", name="UK.Getcover.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2662&awinaffid=125132&clickref=&p=", name="UKEssays";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1757&awinaffid=125132&clickref=&p=", name="UKHost4u";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1826&awinaffid=125132&clickref=&p=", name="UKSoccershop.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2455&awinaffid=125132&clickref=&p=", name="UK Sport Imports Ltd";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2781&awinaffid=125132&clickref=&p=", name="UK Theatre Tickets";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3186&awinaffid=125132&clickref=&p=", name="UK Tights";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3336&awinaffid=125132&clickref=&p=", name="UK Tool Centre";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2399&awinaffid=125132&clickref=&p=", name="UK Water Features";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2538&awinaffid=125132&clickref=&p=", name="Ulster Weavers Home Fashions";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=806&awinaffid=125132&clickref=&p=", name="Vintage Wine Gifts";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1109&awinaffid=125132&clickref=&p=", name="Virgin Experience Days";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2500&awinaffid=125132&clickref=&p=", name="Virginia Hayward Hampers";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3037&awinaffid=125132&clickref=&p=", name="VivaLaDiva.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1805&awinaffid=125132&clickref=&p=", name="Walktall";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3598&awinaffid=125132&clickref=&p=", name="washbag.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2982&awinaffid=125132&clickref=&p=", name="Webhosting UK";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3264&awinaffid=125132&clickref=&p=", name="Weight World";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2586&awinaffid=125132&clickref=&p=", name="WEXO (Work Experience Online)";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2536&awinaffid=125132&clickref=&p=", name="Wiltshire Farm Foods";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=376&awinaffid=125132&clickref=&p=", name="WorldGallery.co.uk";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2903&awinaffid=125132&clickref=&p=", name="World of Baths";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2241&awinaffid=125132&clickref=&p=", name="worldwide-parcelservices";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=1525&awinaffid=125132&clickref=&p=", name="Yoodoo.com";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=2878&awinaffid=125132&clickref=&p=", name="Zest Beauty";
INSERT INTO shops SET url="http://www.awin1.com/cread.php?awinmid=3104&awinaffid=125132&clickref=&p=", name="Ziinga.com";
